Repository davidjerleke/embla-carousel, pull requests merged in 2023-01, with the labels that each got.

#406 chore(docs): set custom root node for autoplay
  packages/embla-carousel-docs/src/content/pages/plugins/auto-height.md
  packages/embla-carousel-docs/src/content/pages/plugins/autoplay.md
  packages/embla-carousel-docs/src/content/pages/plugins/class-names.md
  packages/embla-carousel-docs/src/content/pages/plugins/wheel-gestures.md
Labels: documentation

#415 Bugfix #414
  package.json
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/SlideSizes.ts
  packages/embla-carousel/src/components/index.ts
Labels: bug

#421 Passive event listeners
  package.json
  packages/embla-carousel-auto-height/package.json
  packages/embla-carousel-autoplay/package.json
  packages/embla-carousel-class-names/package.json
  packages/embla-carousel-docs/package.json
  packages/embla-carousel-react/package.json
  packages/embla-carousel-svelte/package.json
  packages/embla-carousel-vue/package.json
  packages/embla-carousel/package.json
  packages/embla-carousel/src/components/DragHandler.ts
  packages/embla-carousel/src/components/EventStore.ts
Labels: bug, feature request

#423 Handle click prevention on drag automatically
  packages/embla-carousel-docs/src/content/pages/api/methods.md
  packages/embla-carousel/src/components/DragHandler.ts
Labels: feature request, resolved

#426 Dragging not working well in Firefox for desktop
  packages/embla-carousel/src/components/DragHandler.ts
Labels: bug

#428 Migrate to the latest Gatsby version
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .nvmrc
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.3.1.cjs
  .yarn/releases/yarn-berry.cjs
  .yarnrc.yml
  package.json
  packages/embla-carousel-docs/gatsby-browser.js
  packages/embla-carousel-docs/gatsby-config.js
  packages/embla-carousel-docs/gatsby-node.js
  packages/embla-carousel-docs/gatsby-ssr.js
  packages/embla-carousel-docs/package.json
  packages/embla-carousel-docs/src/components/Layout/Layout.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/Code.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/Div.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/Link.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/Pre.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/PrismSyntaxHighlight.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/PrismSyntaxWrapper.tsx
  packages/embla-carousel-docs/src/components/Mdx/Mdx.tsx
  packages/embla-carousel-docs/src/components/Mdx/Styles/code.ts
  packages/embla-carousel-docs/src/components/Mdx/Styles/heading.ts
  packages/embla-carousel-docs/src/components/Page/EditPage.tsx
  packages/embla-carousel-docs/src/components/Routes/Context.tsx
  packages/embla-carousel-docs/src/components/Seo/Seo.tsx
  packages/embla-carousel-docs/src/consts/pageTemplates.ts
  packages/embla-carousel-docs/src/content/pages/api/index.mdx
  packages/embla-carousel-docs/src/content/pages/examples/index.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/index.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/react.md
  packages/embla-carousel-docs/src/content/pages/get-started/svelte.md
  packages/embla-carousel-docs/src/content/pages/get-started/vue.md
  packages/embla-carousel-docs/src/content/pages/guides/click-events.md
  packages/embla-carousel-docs/src/content/pages/guides/index.mdx
  packages/embla-carousel-docs/src/content/pages/guides/previous-and-next-buttons.md
  packages/embla-carousel-docs/src/content/pages/plugins/index.mdx
  packages/embla-carousel-docs/src/templates/404.tsx
  packages/embla-carousel-docs/src/templates/Home.tsx
  packages/embla-carousel-docs/src/templates/Page.tsx
  packages/embla-carousel/src/components/utils.ts
  yarn.lock
Labels: documentation
