Repository davidjerleke/embla-carousel, pull requests merged in 2023-08, with the labels that each got.

#549 Support using tab(focus) to select and navigate carousel
  packages/embla-carousel/src/__tests__/PluginsHandler.test.ts
  packages/embla-carousel/src/components/DragHandler.ts
  packages/embla-carousel/src/components/EmblaCarousel.ts
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/PluginsHandler.ts
  packages/embla-carousel/src/components/ResizeHandler.ts
  packages/embla-carousel/src/components/SlideFocus.ts
  packages/embla-carousel/src/components/SlideRegistry.ts
  packages/embla-carousel/src/components/SlidesHandler.ts
Labels: feature request, resolved

#550 Bugfix #541
  packages/embla-carousel/src/components/ScrollTarget.ts
Labels: bug, resolved

#556 allow peer dep svelte ^4.0.0
  packages/embla-carousel-svelte/package.json
Labels: feature request, svelte
