Repository davidjerleke/embla-carousel, pull requests merged in 2023-12, with the labels that each got.

#651 Bugfix #647
  packages/embla-carousel-react/src/index.ts
  packages/embla-carousel-svelte/src/index.ts
  packages/embla-carousel-vue/src/index.ts
  packages/embla-carousel/src/index.ts
Labels: bug

#659 Bugfix #649
  packages/embla-carousel/src/__tests__/containScroll.test.ts
  packages/embla-carousel/src/__tests__/fixtures/containScroll.fixture.ts
  packages/embla-carousel/src/__tests__/slidesToScroll.test.ts
  packages/embla-carousel/src/components/EmblaCarousel.ts
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/Limit.ts
  packages/embla-carousel/src/components/ScrollContain.ts
  packages/embla-carousel/src/components/SlideRegistry.ts
  packages/embla-carousel/src/components/SlidesToScroll.ts
Labels: bug

#660 Bugfix #644
  packages/embla-carousel-autoplay/src/components/Autoplay.ts
  playgrounds/embla-carousel-playground-vanilla/src/main.css
Labels: bug

#661 Bugfix #643
  packages/embla-carousel-autoplay/src/components/Autoplay.ts
Labels: bug

#664 Move Nodenext support script to Rollup build end hook
  .gitignore
  .prettierignore
  package.json
  packages/embla-carousel-auto-height/rollup.config.js
  packages/embla-carousel-auto-height/src/index.ts
  packages/embla-carousel-autoplay/rollup.config.js
  packages/embla-carousel-autoplay/src/index.ts
  packages/embla-carousel-class-names/rollup.config.js
  packages/embla-carousel-class-names/src/index.ts
  packages/embla-carousel-react/rollup.config.js
  packages/embla-carousel-react/src/index.ts
  packages/embla-carousel-reactive-utils/rollup.config.js
  packages/embla-carousel-svelte/rollup.config.js
  packages/embla-carousel-svelte/src/index.ts
  packages/embla-carousel-vue/rollup.config.js
  packages/embla-carousel-vue/src/index.ts
  packages/embla-carousel/rollup.config.js
  packages/embla-carousel/src/index.ts
  rollup.config.js
  scripts/create-nodenext-support/index.ts
Labels: feature request

#657 Add docs section in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation
