Repository davidjerleke/embla-carousel, pull requests merged in 2023-11, with the labels that each got.

#613 Fix leak in slidesInView event
  packages/embla-carousel/src/components/EmblaCarousel.ts
Labels: bug

#618 Make EmblaEventType extendable for plugins
  packages/embla-carousel-react/src/index.ts
  packages/embla-carousel-svelte/src/index.ts
  packages/embla-carousel-vue/src/index.ts
  packages/embla-carousel/src/components/EventHandler.ts
  packages/embla-carousel/src/index.ts
Labels: feature request

#620 Expose the state for autoplay and events to listen to it
  packages/embla-carousel-autoplay/src/components/Autoplay.ts
  packages/embla-carousel-docs/src/content/pages/api/events.mdx
  packages/embla-carousel-docs/src/content/pages/api/methods.mdx
  packages/embla-carousel-docs/src/content/pages/api/options.mdx
  packages/embla-carousel-docs/src/content/pages/api/plugins.mdx
  packages/embla-carousel-docs/src/content/pages/examples/generator.mdx
  packages/embla-carousel-docs/src/content/pages/examples/predefined.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/cdn.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/module.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/react.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/svelte.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/typescript.md
  packages/embla-carousel-docs/src/content/pages/get-started/vue.mdx
  packages/embla-carousel-docs/src/content/pages/guides/breakpoints.md
  packages/embla-carousel-docs/src/content/pages/guides/previous-and-next-buttons.md
  packages/embla-carousel-docs/src/content/pages/guides/slide-container.md
  packages/embla-carousel-docs/src/content/pages/guides/slide-gaps.md
  packages/embla-carousel-docs/src/content/pages/guides/slide-sizes.md
  packages/embla-carousel-docs/src/content/pages/plugins/autoplay.mdx
Labels: bug, feature request

#630 Bugfix #629.
  packages/embla-carousel-docs/src/components/Hero/HeroBrand.tsx
  packages/embla-carousel-docs/src/components/Hero/HeroUsps.tsx
  packages/embla-carousel/src/__tests__/containScroll.test.ts
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/SlideRegistry.ts
Labels: bug, resolved

#615 Add focus interaction to autoplay
  packages/embla-carousel-autoplay/src/components/Autoplay.ts
  packages/embla-carousel-autoplay/src/components/Options.ts
  packages/embla-carousel-docs/src/content/pages/plugins/autoplay.mdx
Labels: feature request

#633 Make reading element dimensions work regardless of transforms
  packages/embla-carousel-docs/src/components/Examples/createCarouselStyles.ts
  packages/embla-carousel/src/__tests__/constructor.test.ts
  packages/embla-carousel/src/__tests__/fixtures/align.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/axis.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/breakpoints.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/constructor.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/containScroll.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/events.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/loop.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/plugins.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/reInit.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/scrollProgress.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/selectedAndPreviousSnap.fixture.ts
  packages/embla-carousel/src/__tests__/fixtures/slidesToScroll.fixture.ts
  packages/embla-carousel/src/__tests__/mocks/testElements.mock.ts
  packages/embla-carousel/src/__tests__/reInit.test.ts
  packages/embla-carousel/src/__tests__/selectedAndPreviousSnap.test.ts
  packages/embla-carousel/src/components/Axis.ts
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/NodeRects.ts
  packages/embla-carousel/src/components/ResizeHandler.ts
  packages/embla-carousel/src/components/ScrollSnaps.ts
  packages/embla-carousel/src/components/SlideSizes.ts
  packages/embla-carousel/src/components/SlidesToScroll.ts
Labels: feature request, core
