Repository davidjerleke/embla-carousel, pull requests merged in 2023-09, with the labels that each got.

#561 Fix old browsers not support add event to MediaQueryList
  packages/embla-carousel/src/components/EventStore.ts
Labels: bug, resolved

#570 Fix resize handler percision mismatch
  packages/embla-carousel/src/components/ResizeHandler.ts
Labels: bug

#573 Auto generate contributors in README files
  README.md
  package.json
  packages/embla-carousel-auto-height/README.md
  packages/embla-carousel-autoplay/README.md
  packages/embla-carousel-class-names/README.md
  packages/embla-carousel-docs/README.md
  packages/embla-carousel-react/README.md
  packages/embla-carousel-reactive-utils/README.md
  packages/embla-carousel-svelte/README.md
  packages/embla-carousel-vue/README.md
  packages/embla-carousel/README.md
  scripts/create-readmes/create-contributors.ts
  scripts/create-readmes/create-readme.ts
  scripts/create-readmes/index.ts
  scripts/create-readmes/readme-template.md
  yarn.lock
Labels: feature request
