Repository davidjerleke/embla-carousel, pull requests merged in 2023-07, with the labels that each got.

#520 Bugfix #514
  packages/embla-carousel/src/__tests__/ScrollBody.test.ts
  packages/embla-carousel/src/components/Animations.ts
  packages/embla-carousel/src/components/DragHandler.ts
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/ScrollBody.ts
  packages/embla-carousel/src/components/ScrollTo.ts
  packages/embla-carousel/src/components/SlideLooper.ts
Labels: bug, resolved

#521 Bugfix #519
  packages/embla-carousel/src/components/EmblaCarousel.ts
  playgrounds/embla-carousel-playground-react/src/Carousel/Carousel.tsx
Labels: bug, resolved

#524 Make `containScroll: 'trimSnaps'` default
  packages/embla-carousel-docs/src/components/CarouselGenerator/CarouselGeneratorAlignmentSettings.tsx
  packages/embla-carousel-docs/src/components/CarouselGenerator/CarouselGeneratorContext.tsx
  packages/embla-carousel-docs/src/components/Examples/Basic/Align.tsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesDist/IosPicker/EmblaCarouselIosPickerItem.jsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesDist/IosPicker/EmblaCarouselIosPickerItem.tsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesSrc/IosPicker/EmblaCarouselIosPickerItem.tsx
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesDist/IosPicker/EmblaCarousel.js
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesDist/IosPicker/EmblaCarousel.ts
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesSrc/IosPicker/EmblaCarousel.ts
  packages/embla-carousel/src/components/Options.ts
  packages/embla-carousel/src/components/ScrollContain.ts
Labels: feature request

#530 fix: Examples url path corrected
  README.md
Labels: documentation

#537 Bugfix #536
  packages/embla-carousel/src/__tests__/Axis.test.ts
  packages/embla-carousel/src/__tests__/SlidesToScroll.test.ts
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/SlideSizes.ts
  packages/embla-carousel/src/components/SlidesToScroll.ts
  playgrounds/embla-carousel-playground-vanilla/src/Carousel/setupDots.ts
Labels: bug, resolved

#543 Adding a class only to the snapped slide
  packages/embla-carousel-auto-height/src/components/AutoHeight.ts
  packages/embla-carousel-class-names/src/components/ClassNames.ts
  packages/embla-carousel-class-names/src/components/Options.ts
  packages/embla-carousel-class-names/src/components/utils.ts
  packages/embla-carousel-docs/src/components/Examples/Miscellaneous/InfiniteScroll.tsx
  packages/embla-carousel-docs/src/components/Examples/Miscellaneous/LazyLoad.tsx
  packages/embla-carousel-docs/src/components/Examples/Plugins/ClassNames.tsx
  packages/embla-carousel-docs/src/components/Examples/Tween/Parallax.tsx
  packages/embla-carousel-docs/src/components/Examples/createCarouselStyles.ts
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesDist/LazyLoad/EmblaCarousel.jsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesDist/LazyLoad/EmblaCarousel.tsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesSrc/LazyLoad/EmblaCarousel.tsx
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesDist/LazyLoad/EmblaCarousel.js
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesDist/LazyLoad/EmblaCarousel.ts
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesDist/LazyLoad/lazy-load.js
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesDist/LazyLoad/lazy-load.ts
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesSrc/LazyLoad/EmblaCarousel.ts
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesSrc/LazyLoad/lazy-load.ts
  packages/embla-carousel-svelte/rollup.config.js
  packages/embla-carousel-vue/rollup.config.js
  packages/embla-carousel/src/__tests__/EmblaCarousel.test.ts
  packages/embla-carousel/src/__tests__/SlidesInView.test.ts
  packages/embla-carousel/src/components/EmblaCarousel.ts
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/EventHandler.ts
  packages/embla-carousel/src/components/Options.ts
  packages/embla-carousel/src/components/ScrollContain.ts
  packages/embla-carousel/src/components/ScrollProgress.ts
  packages/embla-carousel/src/components/ScrollSnaps.ts
  packages/embla-carousel/src/components/SlideLooper.ts
  packages/embla-carousel/src/components/SlideRegistry.ts
  packages/embla-carousel/src/components/SlidesInView.ts
  packages/embla-carousel/src/components/SlidesToScroll.ts
  packages/embla-carousel/src/components/utils.ts
  playgrounds/embla-carousel-playground-vanilla/index.html
  playgrounds/embla-carousel-playground-vanilla/src/main.ts
Labels: feature request, resolved

#545 Prepare sandbox compilation for Vue and Svelte
  packages/embla-carousel-docs/package.json
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesDist/index.html
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesDist/CarouselGenerator/embla-carousel.html
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesDist/index.html
  packages/embla-carousel/src/__tests__/EmblaCarousel.test.ts
  scripts/sandbox-compile/preserve-empty-lines.ts
  scripts/sandbox-compile/sandbox-compile.ts
  scripts/sandbox-compile/ts-compile.ts
  scripts/tsconfig.node.json
  scripts/utils.ts
Labels: feature request, resolved, vue, svelte
