Repository davidjerleke/embla-carousel, pull requests merged in 2024-04, with the labels that each got.

#786 [Feat]: Add RTL case for slide gaps via CSS in docs
  packages/embla-carousel-docs/src/content/pages/guides/slide-gaps.md
Labels: documentation, resolved

#812 [Bug]: Autoplay fast scroll when opened in a new tab
  packages/embla-carousel-auto-scroll/src/components/AutoScroll.ts
  packages/embla-carousel-autoplay/src/components/Autoplay.ts
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesDist/AutoScroll/EmblaCarousel.jsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesDist/AutoScroll/EmblaCarousel.tsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesDist/Autoplay/EmblaCarousel.jsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesDist/Autoplay/EmblaCarousel.tsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesSrc/AutoScroll/EmblaCarousel.tsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesSrc/Autoplay/EmblaCarousel.tsx
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesDist/InfiniteScroll/EmblaCarouselInfiniteScroll.js
Labels: bug, resolved

#844 chore(docs): note about Vue 2 support
  packages/embla-carousel-docs/src/content/pages/get-started/vue.mdx
Labels: documentation

#836 chore(docs): note about reactive options
  packages/embla-carousel-docs/src/content/pages/api/events.mdx
  packages/embla-carousel-docs/src/content/pages/api/methods.mdx
  packages/embla-carousel-docs/src/content/pages/api/options.mdx
  packages/embla-carousel-docs/src/content/pages/api/plugins.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/react.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/solid.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/svelte.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/vue.mdx
Labels: documentation

#830 [Feat]: Add robust pinch zoom support
  packages/embla-carousel-docs/src/components/Examples/examplesCarouselStyles.ts
  packages/embla-carousel/src/components/DragHandler.ts
Labels: feature request, resolved, core
