Repository davidjerleke/embla-carousel, pull requests merged in 2024-01, with the labels that each got.

#677 Bugfix #672
  packages/embla-carousel-auto-height/package.json
  packages/embla-carousel-autoplay/package.json
  packages/embla-carousel-class-names/package.json
  packages/embla-carousel-react/package.json
  packages/embla-carousel-reactive-utils/package.json
  packages/embla-carousel-svelte/package.json
  packages/embla-carousel-vue/package.json
  packages/embla-carousel/package.json
  packages/embla-carousel/src/components/Animations.ts
  packages/embla-carousel/src/components/DragHandler.ts
  packages/embla-carousel/src/components/EmblaCarousel.ts
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/ScrollTo.ts
  rollup.config.js
Labels: bug

#673 Use `onBeforeUnmount` instead of `onUnmounted` to separate embla DOM cleanup from Vue Reactivity
  packages/embla-carousel-vue/src/components/emblaCarouselVue.ts
Labels: feature request, vue

#681 Relocating `CONTRIBUTING.md` to root directory
  CONTRIBUTING.md
Labels: documentation

#682 Bugfix #652
  packages/embla-carousel/src/components/Engine.ts
  packages/embla-carousel/src/components/ScrollTo.ts
Labels: bug, resolved

#685 Added `embla-carousel` as a dependency for CodeSandbox template
  packages/embla-carousel-docs/package.json
  packages/embla-carousel-docs/src/components/Sandbox/React/createSandboxReactPackageJson.ts
  yarn.lock
Labels: bug, documentation, resolved

#683 Development walkthrough in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, resolved

#671 Improve bug report and feature request templates
  .github/DISCUSSION_TEMPLATE/help.yml
  .github/DISCUSSION_TEMPLATE/ideas.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#699 fix(build): update package.json files with correct "module" field
  packages/embla-carousel-auto-height/package.json
  packages/embla-carousel-autoplay/package.json
  packages/embla-carousel-class-names/package.json
  packages/embla-carousel-react/package.json
  packages/embla-carousel-reactive-utils/package.json
  packages/embla-carousel-solid/package.json
  packages/embla-carousel-svelte/package.json
  packages/embla-carousel-vue/package.json
  packages/embla-carousel/package.json
  rollup.config.js
Labels: bug

#704 Update previous-and-next-buttons.md
  packages/embla-carousel-docs/src/content/pages/guides/previous-and-next-buttons.md
Labels: documentation

#714 [Bug]: Synced tabs doesn't always restore scroll position when selected tab changes
  packages/embla-carousel-docs/src/components/Mdx/Styles/index.ts
  packages/embla-carousel-docs/src/components/SiteNavigation/SiteNavigationMenuCompact.tsx
  packages/embla-carousel-docs/src/components/SiteNavigation/SiteNavigationSubMenu.tsx
  packages/embla-carousel-docs/src/components/TableOfContents/TableOfContentsMenu.tsx
  packages/embla-carousel-docs/src/components/Tabs/Tabs.tsx
  packages/embla-carousel-docs/src/components/Tabs/TabsButton.tsx
  packages/embla-carousel-docs/src/components/Tabs/TabsItem.tsx
  packages/embla-carousel-docs/src/components/Tabs/TabsList.tsx
  packages/embla-carousel-docs/src/components/Tabs/TabsPanel.tsx
  packages/embla-carousel-docs/src/consts/tabs.ts
  packages/embla-carousel-docs/src/content/pages/api/events.mdx
  packages/embla-carousel-docs/src/content/pages/api/methods.mdx
  packages/embla-carousel-docs/src/content/pages/api/options.mdx
  packages/embla-carousel-docs/src/content/pages/api/plugins.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/module.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/react.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/solid.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/svelte.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/vue.mdx
  packages/embla-carousel-docs/src/content/pages/plugins/auto-height.mdx
  packages/embla-carousel-docs/src/content/pages/plugins/autoplay.mdx
  packages/embla-carousel-docs/src/content/pages/plugins/class-names.mdx
  packages/embla-carousel-docs/src/content/pages/plugins/wheel-gestures.mdx
  packages/embla-carousel-docs/src/utils/tabs.ts
Labels: bug, documentation

#701 [Feat]: For Vue docs, use a more common SFC format
  packages/embla-carousel-docs/src/components/Mdx/Components/PrismSyntaxHighlight.tsx
  packages/embla-carousel-docs/src/content/pages/api/events.mdx
  packages/embla-carousel-docs/src/content/pages/api/methods.mdx
  packages/embla-carousel-docs/src/content/pages/api/options.mdx
  packages/embla-carousel-docs/src/content/pages/api/plugins.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/react.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/vue.mdx
  packages/embla-carousel-docs/src/utils/prismHighlight.ts
Labels: feature request, documentation, vue

#725 [Feat]: API section in docs - Add code examples for all wrappers
  packages/embla-carousel-docs/package.json
  packages/embla-carousel-docs/src/components/Header/HeaderLogo.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/Blockquote.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/Hr.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/Link.tsx
  packages/embla-carousel-docs/src/components/Mdx/Components/PrismSyntaxHighlight.tsx
  packages/embla-carousel-docs/src/components/Mdx/Mdx.tsx
  packages/embla-carousel-docs/src/components/Mdx/Styles/blockquote.ts
  packages/embla-carousel-docs/src/components/Mdx/Styles/code.ts
  packages/embla-carousel-docs/src/components/Mdx/Styles/heading.ts
  packages/embla-carousel-docs/src/components/Mdx/Styles/hr.ts
  packages/embla-carousel-docs/src/components/Mdx/Styles/index.ts
  packages/embla-carousel-docs/src/components/Mdx/Styles/link.ts
  packages/embla-carousel-docs/src/components/Sandbox/SandboxSelection.tsx
  packages/embla-carousel-docs/src/components/SiteLogo/SiteLogo.tsx
  packages/embla-carousel-docs/src/components/SiteNavigation/SiteNavigationMenuCompact.tsx
  packages/embla-carousel-docs/src/components/Tabs/TabsButton.tsx
  packages/embla-carousel-docs/src/components/Tabs/TabsList.tsx
  packages/embla-carousel-docs/src/consts/prismHighlight.ts
  packages/embla-carousel-docs/src/consts/scrollBars.ts
  packages/embla-carousel-docs/src/content/pages/api/events.mdx
  packages/embla-carousel-docs/src/content/pages/api/methods.mdx
  packages/embla-carousel-docs/src/content/pages/api/options.mdx
  packages/embla-carousel-docs/src/content/pages/api/plugins.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/cdn.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/module.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/react.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/solid.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/svelte.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/vue.mdx
  yarn.lock
Labels: feature request
