Repository davidjerleke/embla-carousel, pull requests merged in 2024-02, with the labels that each got.

#729 Update 'events' Typescript example useEffect deps
  packages/embla-carousel-docs/src/content/pages/api/events.mdx
Labels: documentation

#728 [Bug]: UI issues when removing slides
  packages/embla-carousel/src/components/Animations.ts
Labels: bug

#751 [Bug]: Autoplay and AutoScroll not destroyed properly
  packages/embla-carousel-auto-scroll/src/components/AutoScroll.ts
  packages/embla-carousel-autoplay/src/components/Autoplay.ts
Labels: bug, resolved

#627 [Feat]: Angular wrapper
  packages/embla-carousel-docs/static/angular-logo.svg
  scripts/create-readmes/readme-template.md
Labels: feature request, angular

#758 Fixing a typo in the documentation
  packages/embla-carousel-docs/src/content/pages/get-started/module.mdx
Labels: documentation, resolved

#772 [Bug]: Input click block after dragging
  packages/embla-carousel/src/components/DragHandler.ts
Labels: bug
