Repository davidjerleke/embla-carousel, pull requests merged in 2024-05, with the labels that each got.

#875 [Feat]: Add slideFocus event
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesSrc/CarouselGenerator/EmblaCarouselArrowButtons.tsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesSrc/CarouselGenerator/EmblaCarouselDotButton.tsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesSrc/EmblaCarouselArrowButtons.tsx
  packages/embla-carousel-docs/src/components/Sandbox/React/SandboxFilesSrc/EmblaCarouselDotButton.tsx
  packages/embla-carousel-docs/src/content/pages/api/events.mdx
  playgrounds/embla-carousel-playground-react/src/Carousel/Carousel.tsx
  playgrounds/embla-carousel-playground-solid/src/Carousel/Carousel.tsx
  playgrounds/embla-carousel-playground-vanilla/src/Carousel/setupButtons.ts
  playgrounds/embla-carousel-playground-vanilla/src/main.ts
Labels: feature request

#878 chore(docs): fix missing sandbox dependency and add vanilla examples
  packages/embla-carousel-docs/src/components/Sandbox/Vanilla/SandboxFilesSrc/Fade/EmblaCarousel.ts
  packages/embla-carousel-docs/src/consts/sandbox.ts
Labels: bug, documentation

#880 [Feat]: Fade in pairs
  .github/DISCUSSION_TEMPLATE/general.yml
  .github/DISCUSSION_TEMPLATE/help.yml
  .github/DISCUSSION_TEMPLATE/ideas.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  CONTRIBUTING.md
  packages/embla-carousel-docs/src/components/Examples/Plugins/Fade.tsx
  packages/embla-carousel-fade/src/components/Fade.ts
Labels: feature request, plugin

#882 [Bug]: Image disperses after window resize
  packages/embla-carousel-fade/src/components/Fade.ts
Labels: bug

#885 [Bug]: Fade plugin has wrong peer dependency version
  packages/embla-carousel-fade/package.json
  yarn.lock
Labels: bug, dependencies, plugin
