Repository davidjerleke/embla-carousel, pull requests merged in 2024-09, with the labels that each got.

#992 [Feat]: Adding updated `onemblaInit` naming for Svelte 5
  packages/embla-carousel-docs/src/content/pages/api/events.mdx
  packages/embla-carousel-docs/src/content/pages/api/methods.mdx
  packages/embla-carousel-docs/src/content/pages/api/plugins.mdx
  packages/embla-carousel-docs/src/content/pages/get-started/svelte.mdx
  packages/embla-carousel-svelte/package.json
  packages/embla-carousel-svelte/src/components/emblaCarouselSvelte.ts
Labels: feature request, resolved, svelte

#999 [Feat]: Upgrade deprecated Node version for GitHub actions
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .nvmrc
  yarn.lock
Labels: feature request

#1012 [Bug]: TypeError: Cannot read properties of undefined (reading 'map') in AutoHeight
  packages/embla-carousel-auto-height/src/components/AutoHeight.ts
Labels: bug, resolved, plugin
